name: projekt
on: push

jobs:
  plot:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4 

      - run: sudo apt-get update
      - run: sudo apt-get install -y texlive-xetex pandoc inkscape

      - run: pip install numpy matplotlib PyMPDATA ipykernel nbconvert

      # Generate PDF with config that preserves SVG
      - run: python -m nbconvert --to pdf --execute shallow_water_works.ipynb --config nbconvert_config.py

      - uses: actions/upload-artifact@v4
        with:
          path: shallow_water_works.pdf
