name: sprawozdanie
on: push 

jobs:
  plot:
    runs-on: ubuntu-22.04
    steps:
      - run: pip install scipy pint open_atmos_jupyter_utils matplotlib nbconvert ipykernel
      - uses: actions/checkout@v4 
      - run: python -m nbconvert --to script --execute mpdata_2d_numpy_only.ipynb
      - uses: actions/upload-artifact@v4
        with:
          path: anim.gif
